name: Gitleaks Scan for Private Repositories

on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}}

      - name: Install Gitleaks
        run: |
          wget https://github.com/zricethezav/gitleaks/releases/download/v7.7.0/gitleaks-linux-amd64
          chmod +x gitleaks-linux-amd64
          mv gitleaks-linux-amd64 /usr/local/bin/gitleaks

      - name: Clone and Scan Repository 1
        env:
          REPO_URL: 'https://github.com/bughuntermarle/Sny-Code-Test'
        run: |
          git clone --depth 1 $REPO_URL
          gitleaks --path=Sny-Code-Test --verbose
          rm -rf Sny-Code-Test
