name: gitleaks
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Organization Repositories
        run: |
          ORG_NAME="bughuntermarle"
          PAGE=1
          PER_PAGE=100
          REPO_LIST=""
          while true; do
            RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/orgs/$ORG_NAME/repos?page=$PAGE&per_page=$PER_PAGE")
            # Parse JSON using Bash
            REPO_URLS=$(echo "$RESPONSE" | grep -o 'clone_url": "[^"]*' | awk -F'": "' '{print $2}')
            if [ -z "$REPO_URLS" ]; then
              break
            fi
            REPO_LIST="$REPO_LIST$REPO_URLS\n"
            PAGE=$((PAGE+1))
          done
          echo -e "$REPO_LIST" > org_repo_list.txt

      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}}
