name: Tfsec Checks on Terraform Code

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write
  security-events: write

jobs:
  tfsec-checks:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run Tfsec
        uses: aquasecurity/tfsec-action@v1.0.3

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: tfsec.sarif
