name: Tfsec Checks on Terraform Code

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  tfsec-checks:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run Tfsec
        uses: aquasecurity/tfsec-action@v1.0.3

      - name: Send Slack Alerts
        if: failure()
        run: |
          curl -X POST -H "Content-type: application/json" --data '{
            "text": "Terraform security scan has completed successfully for this pull request.",
            "channel": "#general", # Replace with your Slack channel
            "username": "GitHub Actions"
          }' $SLACK_WEBHOOK_URL
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
