name: tfsec
on:
  pull_request:
  
permissions: 
      contents: read
      pull-requests: write
jobs:
  tfsec-pr-commenter:
    name: tfsec PR commenter
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - name: tfsec
        uses: tfsec/tfsec-pr-commenter-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
